apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: helm
helmCharts:
  - name: go-feed
    releaseName: go-feed
    namespace: default
    valuesFile: helm/go-feed/values.yaml
resources:
  - kube-manifests/HTTProute.yaml
  - kube-manifests/target-grp.yaml
  - k8s/gateway/gateway-class.yaml
  - k8s/gateway/lbconfig.yaml
  - k8s/gateway/gateway.yaml
  - argocd/argo-tg-config.yaml
  - k8s/external-secrets/cluster-secret-store-vault.yaml
  - k8s/external-secrets/external-secret.yaml
  - argocd/image-updater.yaml
