apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: helm
helmCharts:
  - name: go-feed
    releaseName: go-feed
    namespace: default
    valuesFile: helm/go-feed/values.yaml
resources:
  - storage/storageclass-gp3.yaml
  - gateway/gateway-class.yaml
  - gateway/lbconfig.yaml
  - gateway/gateway.yaml
  - gateway/httproute.yaml
  - gateway/target-group-configs.yaml
  - argocd/argo-tg-config.yaml
  - argocd/image-updater.yaml
  - external-secrets/cluster-secret-store-vault.yaml
  - external-secrets/external-secret.yaml
