apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # In-cluster Vault service endpoint
      path: "secret"
      version: "v2"
      auth:
        # Production Best Practice: Kubernetes Auth Engine
        # Vault validates the EKS Service Account JWT token automatically.
        kubernetes:
          mountPath: "kubernetes"
          role: "go-feed-vault-role"
          secretRef:
            name: "external-secrets-token"
            namespace: "external-secrets"
            key: "token"
