apiVersion: v1
kind: Service
metadata:
  name: go-feed-frontend
  namespace: default
  labels:
    app: go-feed-frontend
spec:
  selector:
    app: go-feed-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
