apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: go-feed-lbconfig
  namespace: default
spec:
  scheme: internet-facing

  # Uncomment when ACM certificate/domain is ready:
  # listenerConfigurations:
  #   - protocolPort: HTTPS:443
  #     defaultCertificate: arn:aws:acm:us-east-1:643681121226:certificate/851d88a0-55ea-41e8-94b0-055c408d4c49
